//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableExchangeRate
    {
        public string Title { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public Nullable<double> Description { get; set; }
        public Nullable<int> Quant { get; set; }
        public string Index { get; set; }
        public Nullable<double> Change { get; set; }
    }
}
